#ifndef FLUTTER_PLUGIN_WORKMANAGER_SHAREDPREFERENCE_HELPER_H_
#define FLUTTER_PLUGIN_WORKMANAGER_SHAREDPREFERENCE_HELPER_H_

#include <app_preference.h>

const char* DISPATHCER_HANDLE_KEY = "WMANAGER_TIZEN_DISPATCHER_HANDLE_KEY";

#endif // FLUTTER_PLUGIN_WORKMANAGER_SHAREDPREFERENCE_HELPER_H_